import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

/**
 * Hook to fetch the pre-rendered HTML for a shared report.
 * Returns the static HTML string generated by pms-orchestrate-report.
 */
export const useSharedReport = (shareToken: string | undefined) => {
  return useQuery({
    queryKey: ["shared-report", shareToken],
    queryFn: async (): Promise<string | null> => {
      if (!shareToken) return null;

      // Fetch only the pre-rendered HTML - no complex data mapping needed
      const { data, error } = await supabase
        .from("tb_pms_reports")
        .select("share_html")
        .eq("share_token", shareToken)
        .eq("share_enabled", true)
        .maybeSingle();

      if (error) {
        console.error("Error fetching shared report:", error);
        return null;
      }

      // Return the HTML string (or null if not available)
      return data?.share_html || null;
    },
    enabled: !!shareToken,
    staleTime: 1000 * 60 * 10, // 10 minutes cache - static content
    retry: 1, // Only retry once for invalid tokens
  });
};
