INSERT INTO public.tb_pms_mvp_features (feature_id, feature_name, feature_description, feature_category, complexity_weight) VALUES
('auth', 'User Registration & Authentication', 'User signup, login, password recovery and session management', 'essential', 1),
('profiles', 'Basic User Profiles', 'User profile pages with basic information and settings', 'essential', 1),
('crud', 'Simple Database CRUD Operations', 'Create, read, update and delete operations for core entities', 'essential', 1),
('reporting', 'Basic Reporting & Analytics', 'Simple dashboards with key metrics and basic charts', 'essential', 1),
('notifications', 'Email Notifications', 'Transactional emails for key user actions and events', 'essential', 1),
('admin', 'Basic Admin Panel', 'Administrative interface for managing users and content', 'essential', 1),
('responsive', 'Mobile Responsive Design', 'Responsive layouts that work on mobile, tablet and desktop', 'essential', 1),
('security', 'Basic Security Measures', 'Input validation, HTTPS, rate limiting and basic security headers', 'essential', 1),
('advancedAnalytics', 'Advanced Analytics Dashboard', 'Interactive dashboards with filters, date ranges and data export', 'advanced', 2),
('apiIntegrations', 'Third-party API Integrations', 'Integration with external services like CRMs, ERPs or communication tools', 'advanced', 2),
('payments', 'Payment Processing & Billing', 'Subscription billing, one-time payments and invoice management', 'advanced', 2),
('roles', 'Multi-user Roles & Permissions', 'Role-based access control with customizable permission levels', 'advanced', 2),
('search', 'Advanced Search & Filtering', 'Full-text search with faceted filters and sorting options', 'advanced', 2),
('fileUpload', 'File Upload & Management', 'File upload, storage, preview and management capabilities', 'advanced', 2),
('realtime', 'Real-time Updates', 'Live data updates using websockets or server-sent events', 'advanced', 2),
('workflows', 'Custom Workflows', 'Configurable business process workflows with status tracking', 'advanced', 2),
('advancedReporting', 'Advanced Reporting Tools', 'Custom report builder with scheduling and multiple export formats', 'advanced', 2),
('emailMarketing', 'Email Marketing Integration', 'Email campaign management, templates and subscriber segmentation', 'advanced', 2),
('ai', 'AI/Machine Learning Capabilities', 'AI-powered features like recommendations, predictions or NLP', 'professional', 3),
('dataAnalytics', 'Advanced Data Analytics', 'Big data processing, predictive analytics and data pipelines', 'professional', 3),
('multiTenant', 'Multi-tenant Architecture', 'Isolated data and configuration per tenant with shared infrastructure', 'professional', 3),
('sso', 'SSO & Enterprise Security', 'Single sign-on, SAML/OIDC, audit logs and compliance features', 'professional', 3),
('customIntegrations', 'Custom Integrations', 'Custom-built integrations with proprietary or legacy systems', 'professional', 3),
('apiManagement', 'Advanced API Management', 'API gateway, versioning, rate limiting and developer portal', 'professional', 3),
('collaboration', 'Real-time Collaboration Tools', 'Multi-user editing, comments, mentions and activity feeds', 'professional', 3),
('automation', 'Advanced Automation', 'Complex automation rules, triggers and scheduled tasks', 'professional', 3),
('customReporting', 'Custom Reporting Engine', 'Drag-and-drop report builder with custom formulas and visualizations', 'professional', 3),
('support', 'Enterprise-grade Support', 'Ticketing system, SLA management and knowledge base', 'professional', 3);