
UPDATE public.tb_pms_mvp_features SET feature_description = 'User registration, login, password reset, and session management with JWT tokens. Essential for any SaaS requiring user accounts.' WHERE feature_id = 'auth';
UPDATE public.tb_pms_mvp_features SET feature_description = 'User profile pages with editable fields (name, email, avatar), account settings, and notification preferences.' WHERE feature_id = 'profiles';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Create, Read, Update, Delete operations for core entities with forms, list views, pagination, and validation.' WHERE feature_id = 'crud';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Basic analytics dashboard with KPI cards, simple charts, and usage metrics overview.' WHERE feature_id = 'reporting';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Automated transactional emails for key events: welcome, password reset, status changes, and alerts.' WHERE feature_id = 'notifications';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Admin panel for user management, content moderation, and system configuration. Protected area for operators.' WHERE feature_id = 'admin';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Fully responsive design adapting to mobile, tablet, and desktop with touch-friendly interactions.' WHERE feature_id = 'responsive';
UPDATE public.tb_pms_mvp_features SET feature_description = 'HTTPS, input validation, CSRF protection, rate limiting, and data encryption. Essential security baseline.' WHERE feature_id = 'security';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Payment processing with Stripe/similar, subscription billing, invoicing, and webhook handling.' WHERE feature_id = 'payments';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Email marketing integration for campaigns, subscriber management, and audience segmentation.' WHERE feature_id = 'emailMarketing';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Role-based access control (RBAC) with predefined roles, permission levels, and access restrictions.' WHERE feature_id = 'roles';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Full-text search with filters, sorting, autocomplete, and paginated results across entities.' WHERE feature_id = 'search';
UPDATE public.tb_pms_mvp_features SET feature_description = 'File upload, storage, and management with drag-and-drop, preview, and organized file library.' WHERE feature_id = 'fileUpload';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Live data sync via WebSockets pushing updates to clients without page refresh.' WHERE feature_id = 'realtime';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Configurable multi-step workflows with status transitions, approval chains, and automated triggers.' WHERE feature_id = 'workflows';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Custom report builder with scheduled delivery, multiple export formats, and drill-down analysis.' WHERE feature_id = 'advancedReporting';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Interactive analytics with custom date ranges, multiple chart types, drill-down, and data export.' WHERE feature_id = 'advancedAnalytics';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Pre-built connectors for third-party services (CRMs, ERPs, marketing tools) with OAuth and webhooks.' WHERE feature_id = 'apiIntegrations';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Enterprise support with ticketing system, SLA management, knowledge base, and live chat.' WHERE feature_id = 'support';
UPDATE public.tb_pms_mvp_features SET feature_description = 'AI/ML capabilities: content generation, smart recommendations, NLP, predictive analytics.' WHERE feature_id = 'ai';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Big data processing, statistical analysis, predictive modeling, and data pipeline management.' WHERE feature_id = 'dataAnalytics';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Multi-tenant architecture with data isolation, per-tenant config, and organization management.' WHERE feature_id = 'multiTenant';
UPDATE public.tb_pms_mvp_features SET feature_description = 'SSO with SAML 2.0/OIDC, audit logging, compliance features, and enterprise security controls.' WHERE feature_id = 'sso';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Custom integration layer for proprietary/legacy systems with ETL pipelines and protocol adapters.' WHERE feature_id = 'customIntegrations';
UPDATE public.tb_pms_mvp_features SET feature_description = 'API gateway with rate limiting, versioning, documentation, API keys, and usage analytics.' WHERE feature_id = 'apiManagement';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Real-time co-editing, presence indicators, commenting, and shared workspaces for team collaboration.' WHERE feature_id = 'collaboration';
UPDATE public.tb_pms_mvp_features SET feature_description = 'Advanced automation engine with complex rules, multi-condition triggers, and scheduled tasks.' WHERE feature_id = 'automation';
UPDATE public.tb_pms_mvp_features SET feature_description = 'User-facing drag-and-drop report builder with custom metrics, formulas, and sharing capabilities.' WHERE feature_id = 'customReporting';
