-- Add hero_score_section column to store score and tagline from n8n workflow
ALTER TABLE tb_pms_reports
ADD COLUMN hero_score_section jsonb DEFAULT '{}'::jsonb;

COMMENT ON COLUMN tb_pms_reports.hero_score_section IS 
'Stores hero score data: score (number 0-100) and tagline phrase generated by n8n workflow';