-- Add summary_section column to store executive summary data from n8n workflow
ALTER TABLE tb_pms_reports
ADD COLUMN summary_section jsonb DEFAULT '{}'::jsonb;

COMMENT ON COLUMN tb_pms_reports.summary_section IS 
'Stores executive summary data: verdict recommendation and summary paragraphs generated by n8n workflow';