-- Add business_plan_section column to tb_pms_reports
ALTER TABLE public.tb_pms_reports
ADD COLUMN IF NOT EXISTS business_plan_section jsonb DEFAULT '{}'::jsonb;

-- Add comment for documentation
COMMENT ON COLUMN public.tb_pms_reports.business_plan_section IS 
'Complete Business Plan document containing: title, subtitle, viability_score, viability_label, markdown_content, charts_data, word_count. Generated by n8n Business Plan AI pipeline.';