-- Create newsletter subscriptions table
CREATE TABLE public.tb_web_newsletter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  source TEXT DEFAULT 'website',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  
  -- Ensure unique emails (prevent duplicates)
  CONSTRAINT tb_web_newsletter_email_unique UNIQUE (email)
);

-- Add comment to table
COMMENT ON TABLE public.tb_web_newsletter IS 'Stores newsletter subscription emails';

-- Enable Row Level Security
ALTER TABLE public.tb_web_newsletter ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert (subscribe)
CREATE POLICY "Anyone can subscribe to newsletter"
  ON public.tb_web_newsletter
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);